# Generated by Django 3.0.5 on 2021-03-03 05:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cricketer_Name', models.CharField(max_length=50)),
                ('Cricketer_Age', models.IntegerField(max_length=3)),
                ('Cricketer_Team_Name', models.CharField(max_length=255)),
                ('Batsman', models.BooleanField(default=False)),
                ('Bowler', models.BooleanField(default=False)),
                ('No_of_catches', models.CharField(max_length=255, null=True)),
                ('No_of_Matches', models.CharField(max_length=255, null=True)),
                ('Strike_Rate', models.CharField(max_length=255, null=True)),
                ('user_details', djongo.models.fields.JSONField()),
            ],
        ),
    ]
